#!/bin/bash
echo("ingrese el n1")
read n1
echo ("ingrese el n2")
read n2
multiplicacion = expr n1 \* n2
echo ("multiplicacion $multiplicacion")
suma = n1 + n2
echo("suma $suma")
resta = n1 - n2
if [$"n1" >"$n2"]
then
	echo("$n1 es mayor")
elif
	echo("$n2 es mayor")
fi
exit
